In [18]:
pip install pandas matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (2.3.3)
Requirement already satisfied: matplotlib in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (3.10.8)
Requirement already satisfied: seaborn in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (12.1.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in C:\Users\harsha vardhan\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [19]:
import pandas as pd

df = pd.read_csv("../data/cleaned_supply_chain.csv")

df.head()

,Order Id,Type,Order Status,order_date,shipping_date,Days for shipping (real),Days for shipment (scheduled),delivery_delay,is_late,Delivery Status,...,Customer Id,Customer Segment,Customer City,Customer State,Customer Country,Market,Order Region,Order Country,Order City,Order State
0,1,DEBIT,PENDING,2015-04-13,2015-04-16,3,4,-1,0,Shipping canceled,...,2847,Corporate,Los Angeles,TX,EE. UU.,USCA,Central America,Mexico,Miami,NY
1,2,CASH,ON_HOLD,2016-03-11,2016-03-13,2,3,-1,0,Advance shipping,...,7851,Home Office,Caguas,TX,India,Europe,Southern Asia,Mexico,New York,NY
2,3,CASH,SUSPECTED_FRAUD,2017-05-10,2017-05-16,6,3,3,1,Shipping on time,...,8211,Consumer,Los Angeles,TX,Germany,Africa,Western Europe,France,Los Angeles,FL
3,4,PAYMENT,COMPLETE,2015-09-28,2015-10-04,6,4,2,1,Advance shipping,...,8865,Consumer,New York,IL,Mexico,Pacific Asia,Western Europe,Mexico,Managua,TX
4,5,CASH,SUSPECTED_FRAUD,2015-04-17,2015-04-19,2,3,-1,0,Advance shipping,...,4317,Home Office,Los Angeles,NaN,Mexico,Europe,Central America,El Salvador,Los Angeles,IL

In [20]:
df.shape

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 36 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Order Id                       500 non-null    int64
 1   Type                           500 non-null    object
 2   Order Status                   500 non-null    object
 3   order_date                     500 non-null    object
 4   shipping_date                  500 non-null    object
 5   Days for shipping (real)       500 non-null    int64
 6   Days for shipment (scheduled)  500 non-null    int64
 7   delivery_delay                 500 non-null    int64
 8   is_late                        500 non-null    int64
 9   Delivery Status                500 non-null    object
 10  Late_delivery_risk             500 non-null    int64
 11  Shipping Mode                  500 non-null    object
 12  Sales                          492 non-null    float64
 13  Order Item Quantity            500 non-null    int64
 14  Order Item Discount            500 non-null    float64
 15  Order Item Discount Rate       500 non-null    float64
 16  Order Item Product Price       500 non-null    float64
 17  Order Item Profit Ratio        500 non-null    float64
 18  Order Profit Per Order         500 non-null    float64
 19  Benefit per order              500 non-null    float64
 20  profit_margin                  492 non-null    float64
 21  Product Name                   500 non-null    object
 22  Product Price                  500 non-null    float64
 23  Product Status                 500 non-null    int64
 24  Category Name                  500 non-null    object
 25  Department Name                500 non-null    object
 26  Customer Id                    500 non-null    int64
 27  Customer Segment               500 non-null    object
 28  Customer City                  492 non-null    object
 29  Customer State                 492 non-null    object
 30  Customer Country               500 non-null    object
 31  Market                         500 non-null    object
 32  Order Region                   492 non-null    object
 33  Order Country                  500 non-null    object
 34  Order City                     500 non-null    object
 35  Order State                    500 non-null    object
dtypes: float64(9), int64(9), object(18)
memory usage: 140.8+ KB

In [21]:
df['delivery_delay'].describe()

count    500.000000
mean       1.548000
std        1.746366
min       -1.000000
25%        0.000000
50%        2.000000
75%        3.000000
max        4.000000
Name: delivery_delay, dtype: float64

In [22]:
df['is_late'].value_counts(normalize=True) * 100

is_late
1    67.2
0    32.8
Name: proportion, dtype: float64

In [23]:
df.columns

Index(['Order Id', 'Type', 'Order Status', 'order_date', 'shipping_date',
       'Days for shipping (real)', 'Days for shipment (scheduled)',
       'delivery_delay', 'is_late', 'Delivery Status', 'Late_delivery_risk',
       'Shipping Mode', 'Sales', 'Order Item Quantity', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Profit Per Order',
       'Benefit per order', 'profit_margin', 'Product Name', 'Product Price',
       'Product Status', 'Category Name', 'Department Name', 'Customer Id',
       'Customer Segment', 'Customer City', 'Customer State',
       'Customer Country', 'Market', 'Order Region', 'Order Country',
       'Order City', 'Order State'],
      dtype='object')

In [24]:
df.groupby('Order Region')['delivery_delay'].mean().sort_values(ascending=False)

Order Region
Southern Asia      1.989474
Central America    1.550000
Western Europe     1.542857
Eastern US         1.394231
Western US         1.261364
Name: delivery_delay, dtype: float64

In [25]:
df.groupby('Shipping Mode')['delivery_delay'].mean()

Shipping Mode
First Class       1.591667
Same Day          1.818898
Second Class      1.422222
Standard Class    1.355932
Name: delivery_delay, dtype: float64

In [26]:
df[df['Order Profit Per Order'] < 0]

,Order Id,Type,Order Status,order_date,shipping_date,Days for shipping (real),Days for shipment (scheduled),delivery_delay,is_late,Delivery Status,...,Customer Id,Customer Segment,Customer City,Customer State,Customer Country,Market,Order Region,Order Country,Order City,Order State
18,19,TRANSFER,PENDING,2016-10-25,2016-10-29,4,5,-1,0,Shipping on time,...,8467,Home Office,Miami,TX,Germany,Africa,Eastern US,Mexico,San Jose,CA
20,21,DEBIT,ON_HOLD,2016-10-23,2016-10-29,6,2,4,1,Shipping on time,...,1579,Home Office,Miami,TX,France,Africa,Western Europe,El Salvador,Managua,NY
29,30,TRANSFER,PENDING,2017-08-13,2017-08-15,2,3,-1,0,Late delivery,...,2381,Home Office,Miami,CA,Mexico,USCA,Western US,United States,Los Angeles,CA
30,31,PAYMENT,CANCELED,2015-10-04,2015-10-07,3,4,-1,0,Late delivery,...,9154,Corporate,Los Angeles,CA,EE. UU.,Europe,Southern Asia,United States,San Jose,CA
42,43,DEBIT,CLOSED,2016-11-12,2016-11-13,1,2,-1,0,Late delivery,...,4645,Home Office,Chicago,TX,EE. UU.,Pacific Asia,Southern Asia,El Salvador,Miami,FL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
477,478,TRANSFER,PENDING,2015-12-15,2015-12-19,4,3,1,1,Shipping canceled,...,9488,Consumer,New York,CA,Mexico,Europe,Western Europe,El Salvador,Miami,NY
482,483,DEBIT,CANCELED,2015-04-09,2015-04-14,5,4,1,1,Advance shipping,...,1175,Home Office,Miami,FL,EE. UU.,Pacific Asia,Western US,El Salvador,Miami,IL
485,486,PAYMENT,PENDING,2015-04-26,2015-05-03,7,4,3,1,Shipping on time,...,2667,Consumer,Caguas,CA,EE. UU.,LATAM,Eastern US,United States,Los Angeles,NY
491,492,TRANSFER,CLOSED,2015-06-10,2015-06-15,5,4,1,1,Shipping canceled,...,4259,Corporate,Chicago,FL,France,Europe,Western Europe,Mexico,Managua,FL
494,495,TRANSFER,CANCELED,2015-05-08,2015-05-17,9,5,4,1,Late delivery,...,6231,Home Office,NaN,FL,EE. UU.,Africa,Southern Asia,France,Los Angeles,IL

In [27]:
df.groupby('Product Name')[['Sales','Order Profit Per Order']].sum().sort_values(by='Sales', ascending=False)

                Sales  Order Profit Per Order
Product Name
Product WBGR  1998.72                  606.65
Product EPTC  1992.74                  374.79
Product SCVK  1986.81                  677.19
Product XLCR  1984.42                  469.69
Product WMWO  1983.12                  -91.38
...               ...                     ...
Product ATIY     0.00                   23.74
Product HQPD     0.00                  -65.52
Product KTTZ     0.00                  -32.79
Product GOFZ     0.00                   30.73
Product DSLA     0.00                   14.47

[500 rows x 2 columns]

In [28]:
on_time_rate = (df['is_late'] == 0).mean() * 100

In [29]:
late_rate = (df['is_late'] == 1).mean() * 100

In [30]:
avg_delay = df['delivery_delay'].mean()

In [31]:
profit_margin = (df['Order Profit Per Order'].sum() / df['Sales'].sum()) * 100

In [32]:
revenue_at_risk = df[df['is_late'] == 1]['Sales'].sum()

In [33]:
df.groupby('Shipping Mode')['is_late'].mean() * 100

Shipping Mode
First Class       69.166667
Same Day          70.866142
Second Class      65.185185
Standard Class    63.559322
Name: is_late, dtype: float64